### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by gemal** [sandworm-hq/sandworm-audit#141]
**Sandworm version**
1.53.1

**Describe the bug**
```
sandworm audit
Sandworm 🪱
Security and License Compliance Audit
- Building dependency graph...Exception in PromiseRejectCallback:
c:\AppData\Roaming\npm\node_modules\@sandworm\audit\src\files\workspace.js:61
  return null;

RangeError: Maximum call stack size exceeded


❌ Failed: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at Object.existsSync (node:fs:303:20)
    at loadWorkspace (c:\AppData\Roaming\npm\node_modules\@sandworm\audit\src\files\workspace.js:14:10)
    at loadWorkspace (c:\AppData\Roaming\npm\node_modules\@sandworm\audit\src\files\workspace.js:58:12)
    at loadWorkspace (c:\AppData\Roaming\npm\node_modules\@sandworm\audit\src\files\workspace.js:58:12)
    at loadWorkspace (c:\AppData\Roaming\npm\node_modules\@sandworm\audit\src\files\workspace.js:58:12)
    at loadWorkspace (c:\AppData\Roaming\npm\node_modules\@sandworm\audit\src\files\workspace.js:58:12)
    at loadWorkspace (c:\AppData\Roaming\npm\node_modules\@sandworm\audit\src\files\workspace.js:58:12)
    at loadWorkspace (c:\AppData\Roaming\npm\node_modules\@sandworm\audit\src\files\workspace.js:58:12)
    at loadWorkspace (c:\AppData\Roaming\npm\node_modules\@sandworm\audit\src\files\workspace.js:58:12)
    at loadWorkspace (c:\AppData\Roaming\npm\node_modules\@sandworm\audit\src\files\workspace.js:58:12)

? Send crash report to Sandworm? » - Use arrow-keys. Return to submit.
>   Send with dependency info
    Send without dependency info
    Don't send
| Building dependency graph...

```

**Manifest files**
Whenever possible, please provide your `package.json` manifest file content (or at least a list of all the dependencies within), as well as your lockfile.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**System (please complete the following information):**
npm --version
10.1.0

node --version
v18.17.1

Windows
- Node Version [e.g. 14.17.3]
- Package Manager [e.g. npm]
- Package Manager Version [e.g. 8.5.5]
- OS: [e.g. Ubuntu 22.04]

**Additional context**

**Comment by ClaysonIO** [comment]
I'm also having this issue. I was able to drop down to version [1.43.1](https://www.npmjs.com/package/@sandworm/audit/v/1.43.1) and successfully run the audit by calling `npx @sandworm/audit@1.43.1`
