### ISSUE TITLE
Typeerror on initial run

### ISSUE THREAD

**Issue by karesztrk** [sandworm-hq/sandworm-audit#60]
**Sandworm version**
`1.27.0`

**Describe the bug**
I'm receiving the following error on the first try of any project on any node version (12, 14, 18).
```
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at generateNpmGraph (/home/ktorok/.nvm/versions/node/v14.21.3/lib/node_modules/@sandworm/audit/src/graph/generateNpmGraph.js:14:10)
    at generateGraphPromise (/home/ktorok/.nvm/versions/node/v14.21.3/lib/node_modules/@sandworm/audit/src/graph/index.js:17:19)
    at async getReport (/home/ktorok/.nvm/versions/node/v14.21.3/lib/node_modules/@sandworm/audit/src/index.js:41:25)
    at async Object.handler (/home/ktorok/.nvm/versions/node/v14.21.3/lib/node_modules/@sandworm/audit/src/cli/index.js:36:7)
```

**To Reproduce**
Run `sandworm-audit`

**Expected behavior**
Give me any output without error.

**Node (please complete the following information):**
- Version 12, 14, 18
- OS: Garuda Linux

**Comment by gabidobo** [comment]
@karesztrk thanks for reporting this!

Could you please check your `package-lock.json` file and tell me what your `lockfileVersion` is? We currently support `lockfileVersion` >= 2 and it sounds like yours might be version 1.

We need to do better error messaging around this, I've published v1.28.0 that should log a better error if that's the case - you can try it out with `npx @sandworm/audit@latest` to force npm to get the latest version.

**Comment by karesztrk** [comment]
@gabidobo You are correct. I have a version `"lockfileVersion": 1`. I did not notice that it was a mandatory thing. Thanks for the clarification.

**Comment by gabidobo** [comment]
@karesztrk thank you for bringing this up! I'll also update the docs to highlight these requirements better.
Closing this now.
