### ISSUE TITLE
pnpm monorepo support

### ISSUE THREAD

**Issue by acherkashin** [sandworm-hq/sandworm-audit#67]
**Sandworm version**
1.29.1

**Describe the bug**
Does sandworm-audit supports pnpm monorepos?

In the root of my repository there are 2 files:
- pnpm-lock.yaml
- pnpm-workspace.yaml
 
<img width="376" alt="image" src="https://user-images.githubusercontent.com/9947582/224901019-daae6a0a-1c3b-406d-8aca-a0cc6cc124ae.png">

There is no `package.json` in the same folder with `pnpm-lock.yaml`. At the same time, every package of monorepo has a `package.json`.

When I try to run `sandworm-audit` in the root of the repository, I get the following error.

```
TypeError: Cannot read properties of undefined (reading 'name')
    at generatePnpmGraph (/Users/cherkalexander/.nvm/versions/node/v16.15.1/lib/node_modules/@sandworm/audit/src/graph/generatePnpmGraph.js:15:20)
    at generateGraphPromise (/Users/cherkalexander/.nvm/versions/node/v16.15.1/lib/node_modules/@sandworm/audit/src/graph/index.js:37:19)
    at async getReport (/Users/cherkalexander/.nvm/versions/node/v16.15.1/lib/node_modules/@sandworm/audit/src/index.js:41:25)
    at async Object.handler (/Users/cherkalexander/.nvm/versions/node/v16.15.1/lib/node_modules/@sandworm/audit/src/cli/index.js:43:7)
```

**System (please complete the following information):**
- Node Version - 16.15.1
- Package Manager - PNPM 
- Package Manager Version - 7.17.1
- OS: MacOs

**Additional context**
I tried to use sandworm in a project where yarn 1 is used, and it works great. Thank you for this cool project 👍

**Comment by gabidobo** [comment]
Hi @acherkashin!

Thank you for the kind words 😊 

You are correct - Sandworm doesn't currently support workspaces. I've added some notes in the docs to make this explicit.
Workspaces are definitely on the roadmap, I just need to understand how that feature would look like. If you have any suggestions they are welcome - as a user, how would you like to use Sandworm to audit workspaces?
